set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_C_FLAGS_RELEASE "/Ob3 /GL")
set(VCPKG_CXX_FLAGS_RELEASE "/Ob3 /GL")
set(VCPKG_LINKER_FLAGS_RELEASE "/LTCG")
